import { newIsoCountry, type IsoCountry } from "./isoCountry.js";

/**
 * Ported from NzbDrone.Core/Parser/IsoCountries.cs.
 *
 * See https://wiki.musicbrainz.org/Release_Country for the source list.
 * C# stored this as a `HashSet<IsoCountry>`; ported here as a plain array
 * in the same declared order (iteration order isn't observable through
 * `Find`'s `SingleOrDefault` lookups, but preserving order keeps a diff
 * against the source trivial).
 */
const All: readonly IsoCountry[] = [
  newIsoCountry("AF", "Afghanistan"),
  newIsoCountry("AX", "Åland Islands"),
  newIsoCountry("AL", "Albania"),
  newIsoCountry("DZ", "Algeria"),
  newIsoCountry("AS", "American Samoa"),
  newIsoCountry("AD", "Andorra"),
  newIsoCountry("AO", "Angola"),
  newIsoCountry("AI", "Anguilla"),
  newIsoCountry("AQ", "Antarctica"),
  newIsoCountry("AG", "Antigua and Barbuda"),
  newIsoCountry("AR", "Argentina"),
  newIsoCountry("AM", "Armenia"),
  newIsoCountry("AW", "Aruba"),
  newIsoCountry("AU", "Australia"),
  newIsoCountry("AT", "Austria"),
  newIsoCountry("AZ", "Azerbaijan"),
  newIsoCountry("BS", "Bahamas"),
  newIsoCountry("BH", "Bahrain"),
  newIsoCountry("BD", "Bangladesh"),
  newIsoCountry("BB", "Barbados"),
  newIsoCountry("BY", "Belarus"),
  newIsoCountry("BE", "Belgium"),
  newIsoCountry("BZ", "Belize"),
  newIsoCountry("BJ", "Benin"),
  newIsoCountry("BM", "Bermuda"),
  newIsoCountry("BT", "Bhutan"),
  newIsoCountry("BO", "Bolivia"),
  newIsoCountry("BA", "Bosnia and Herzegovina"),
  newIsoCountry("BW", "Botswana"),
  newIsoCountry("BV", "Bouvet Island"),
  newIsoCountry("BR", "Brazil"),
  newIsoCountry("IO", "British Indian Ocean Territory"),
  newIsoCountry("BN", "Brunei Darussalam"),
  newIsoCountry("BG", "Bulgaria"),
  newIsoCountry("BF", "Burkina Faso"),
  newIsoCountry("BI", "Burundi"),
  newIsoCountry("KH", "Cambodia"),
  newIsoCountry("CM", "Cameroon"),
  newIsoCountry("CA", "Canada"),
  newIsoCountry("CV", "Cape Verde"),
  newIsoCountry("KY", "Cayman Islands"),
  newIsoCountry("CF", "Central African Republic"),
  newIsoCountry("TD", "Chad"),
  newIsoCountry("CL", "Chile"),
  newIsoCountry("CN", "China"),
  newIsoCountry("CX", "Christmas Island"),
  newIsoCountry("CC", "Cocos (Keeling) Islands"),
  newIsoCountry("CO", "Colombia"),
  newIsoCountry("KM", "Comoros"),
  newIsoCountry("CG", "Congo"),
  newIsoCountry("CD", "Congo, The Democratic Republic of the"),
  newIsoCountry("CK", "Cook Islands"),
  newIsoCountry("CR", "Costa Rica"),
  newIsoCountry("CI", "Cote d'Ivoire"),
  newIsoCountry("HR", "Croatia"),
  newIsoCountry("CU", "Cuba"),
  newIsoCountry("CY", "Cyprus"),
  newIsoCountry("XC", "Czechoslovakia"),
  newIsoCountry("CZ", "Czech Republic"),
  newIsoCountry("DK", "Denmark"),
  newIsoCountry("DJ", "Djibouti"),
  newIsoCountry("DM", "Dominica"),
  newIsoCountry("DO", "Dominican Republic"),
  newIsoCountry("XG", "East Germany"),
  newIsoCountry("EC", "Ecuador"),
  newIsoCountry("EG", "Egypt"),
  newIsoCountry("SV", "El Salvador"),
  newIsoCountry("GQ", "Equatorial Guinea"),
  newIsoCountry("ER", "Eritrea"),
  newIsoCountry("EE", "Estonia"),
  newIsoCountry("ET", "Ethiopia"),
  newIsoCountry("XE", "Europe"),
  newIsoCountry("FK", "Falkland Islands (Malvinas)"),
  newIsoCountry("FO", "Faroe Islands"),
  newIsoCountry("FJ", "Fiji"),
  newIsoCountry("FI", "Finland"),
  newIsoCountry("FR", "France"),
  newIsoCountry("GF", "French Guiana"),
  newIsoCountry("PF", "French Polynesia"),
  newIsoCountry("TF", "French Southern Territories"),
  newIsoCountry("GA", "Gabon"),
  newIsoCountry("GM", "Gambia"),
  newIsoCountry("GE", "Georgia"),
  newIsoCountry("DE", "Germany"),
  newIsoCountry("GH", "Ghana"),
  newIsoCountry("GI", "Gibraltar"),
  newIsoCountry("GR", "Greece"),
  newIsoCountry("GL", "Greenland"),
  newIsoCountry("GD", "Grenada"),
  newIsoCountry("GP", "Guadeloupe"),
  newIsoCountry("GU", "Guam"),
  newIsoCountry("GT", "Guatemala"),
  newIsoCountry("GG", "Guernsey"),
  newIsoCountry("GN", "Guinea"),
  newIsoCountry("GW", "Guinea-Bissau"),
  newIsoCountry("GY", "Guyana"),
  newIsoCountry("HT", "Haiti"),
  newIsoCountry("HM", "Heard and Mc Donald Islands"),
  newIsoCountry("HN", "Honduras"),
  newIsoCountry("HK", "Hong Kong"),
  newIsoCountry("HU", "Hungary"),
  newIsoCountry("IS", "Iceland"),
  newIsoCountry("IN", "India"),
  newIsoCountry("ID", "Indonesia"),
  newIsoCountry("IR", "Iran (Islamic Republic of)"),
  newIsoCountry("IQ", "Iraq"),
  newIsoCountry("IE", "Ireland"),
  newIsoCountry("IM", "Isle of Man"),
  newIsoCountry("IL", "Israel"),
  newIsoCountry("IT", "Italy"),
  newIsoCountry("JM", "Jamaica"),
  newIsoCountry("JP", "Japan"),
  newIsoCountry("JE", "Jersey"),
  newIsoCountry("JO", "Jordan"),
  newIsoCountry("KZ", "Kazakhstan"),
  newIsoCountry("KE", "Kenya"),
  newIsoCountry("KI", "Kiribati"),
  newIsoCountry("KP", "Korea (North), Democratic People's Republic of"),
  newIsoCountry("KR", "Korea (South), Republic of"),
  newIsoCountry("KW", "Kuwait"),
  newIsoCountry("KG", "Kyrgyzstan"),
  newIsoCountry("LA", "Lao People's Democratic Republic"),
  newIsoCountry("LV", "Latvia"),
  newIsoCountry("LB", "Lebanon"),
  newIsoCountry("LS", "Lesotho"),
  newIsoCountry("LR", "Liberia"),
  newIsoCountry("LY", "Libyan Arab Jamahiriya"),
  newIsoCountry("LI", "Liechtenstein"),
  newIsoCountry("LT", "Lithuania"),
  newIsoCountry("LU", "Luxembourg"),
  newIsoCountry("MO", "Macau"),
  newIsoCountry("MK", "Macedonia, The Former Yugoslav Republic of"),
  newIsoCountry("MG", "Madagascar"),
  newIsoCountry("MW", "Malawi"),
  newIsoCountry("MY", "Malaysia"),
  newIsoCountry("MV", "Maldives"),
  newIsoCountry("ML", "Mali"),
  newIsoCountry("MT", "Malta"),
  newIsoCountry("MH", "Marshall Islands"),
  newIsoCountry("MQ", "Martinique"),
  newIsoCountry("MR", "Mauritania"),
  newIsoCountry("MU", "Mauritius"),
  newIsoCountry("YT", "Mayotte"),
  newIsoCountry("MX", "Mexico"),
  newIsoCountry("FM", "Micronesia, Federated States of"),
  newIsoCountry("MD", "Moldova, Republic of"),
  newIsoCountry("MC", "Monaco"),
  newIsoCountry("MN", "Mongolia"),
  newIsoCountry("ME", "Montenegro"),
  newIsoCountry("MS", "Montserrat"),
  newIsoCountry("MA", "Morocco"),
  newIsoCountry("MZ", "Mozambique"),
  newIsoCountry("MM", "Myanmar"),
  newIsoCountry("NA", "Namibia"),
  newIsoCountry("NR", "Nauru"),
  newIsoCountry("NP", "Nepal"),
  newIsoCountry("NL", "Netherlands"),
  newIsoCountry("AN", "Netherlands Antilles"),
  newIsoCountry("NC", "New Caledonia"),
  newIsoCountry("NZ", "New Zealand"),
  newIsoCountry("NI", "Nicaragua"),
  newIsoCountry("NE", "Niger"),
  newIsoCountry("NG", "Nigeria"),
  newIsoCountry("NU", "Niue"),
  newIsoCountry("NF", "Norfolk Island"),
  newIsoCountry("MP", "Northern Mariana Islands"),
  newIsoCountry("NO", "Norway"),
  newIsoCountry("OM", "Oman"),
  newIsoCountry("PK", "Pakistan"),
  newIsoCountry("PW", "Palau"),
  newIsoCountry("PS", "Palestinian Territory"),
  newIsoCountry("PA", "Panama"),
  newIsoCountry("PG", "Papua New Guinea"),
  newIsoCountry("PY", "Paraguay"),
  newIsoCountry("PE", "Peru"),
  newIsoCountry("PH", "Philippines"),
  newIsoCountry("PN", "Pitcairn"),
  newIsoCountry("PL", "Poland"),
  newIsoCountry("PT", "Portugal"),
  newIsoCountry("PR", "Puerto Rico"),
  newIsoCountry("QA", "Qatar"),
  newIsoCountry("RE", "Reunion"),
  newIsoCountry("RO", "Romania"),
  newIsoCountry("RU", "Russian Federation"),
  newIsoCountry("RW", "Rwanda"),
  newIsoCountry("BL", "Saint Barthélemy"),
  newIsoCountry("SH", "Saint Helena"),
  newIsoCountry("KN", "Saint Kitts and Nevis"),
  newIsoCountry("LC", "Saint Lucia"),
  newIsoCountry("MF", "Saint Martin"),
  newIsoCountry("PM", "Saint Pierre and Miquelon"),
  newIsoCountry("VC", "Saint Vincent and The Grenadines"),
  newIsoCountry("WS", "Samoa"),
  newIsoCountry("SM", "San Marino"),
  newIsoCountry("ST", "Sao Tome and Principe"),
  newIsoCountry("SA", "Saudi Arabia"),
  newIsoCountry("SN", "Senegal"),
  newIsoCountry("RS", "Serbia"),
  newIsoCountry("CS", "Serbia and Montenegro"),
  newIsoCountry("SC", "Seychelles"),
  newIsoCountry("SL", "Sierra Leone"),
  newIsoCountry("SG", "Singapore"),
  newIsoCountry("SK", "Slovakia"),
  newIsoCountry("SI", "Slovenia"),
  newIsoCountry("SB", "Solomon Islands"),
  newIsoCountry("SO", "Somalia"),
  newIsoCountry("ZA", "South Africa"),
  newIsoCountry("GS", "South Georgia and the South Sandwich Islands"),
  newIsoCountry("SU", "Soviet Union"),
  newIsoCountry("ES", "Spain"),
  newIsoCountry("LK", "Sri Lanka"),
  newIsoCountry("SD", "Sudan"),
  newIsoCountry("SR", "Suriname"),
  newIsoCountry("SJ", "Svalbard and Jan Mayen"),
  newIsoCountry("SZ", "Swaziland"),
  newIsoCountry("SE", "Sweden"),
  newIsoCountry("CH", "Switzerland"),
  newIsoCountry("SY", "Syrian Arab Republic"),
  newIsoCountry("TW", "Taiwan"),
  newIsoCountry("TJ", "Tajikistan"),
  newIsoCountry("TZ", "Tanzania, United Republic of"),
  newIsoCountry("TH", "Thailand"),
  newIsoCountry("TL", "Timor-Leste"),
  newIsoCountry("TG", "Togo"),
  newIsoCountry("TK", "Tokelau"),
  newIsoCountry("TO", "Tonga"),
  newIsoCountry("TT", "Trinidad and Tobago"),
  newIsoCountry("TN", "Tunisia"),
  newIsoCountry("TR", "Turkey"),
  newIsoCountry("TM", "Turkmenistan"),
  newIsoCountry("TC", "Turks and Caicos Islands"),
  newIsoCountry("TV", "Tuvalu"),
  newIsoCountry("UG", "Uganda"),
  newIsoCountry("UA", "Ukraine"),
  newIsoCountry("AE", "United Arab Emirates"),
  newIsoCountry("GB", "United Kingdom"),
  newIsoCountry("US", "United States"),
  newIsoCountry("UM", "United States Minor Outlying Islands"),
  newIsoCountry("XU", "[Unknown Country]"),
  newIsoCountry("UY", "Uruguay"),
  newIsoCountry("UZ", "Uzbekistan"),
  newIsoCountry("VU", "Vanuatu"),
  newIsoCountry("VA", "Vatican City State (Holy See)"),
  newIsoCountry("VE", "Venezuela"),
  newIsoCountry("VN", "Viet Nam"),
  newIsoCountry("VG", "Virgin Islands, British"),
  newIsoCountry("VI", "Virgin Islands, U.S."),
  newIsoCountry("WF", "Wallis and Futuna Islands"),
  newIsoCountry("EH", "Western Sahara"),
  newIsoCountry("XW", "[Worldwide]"),
  newIsoCountry("YE", "Yemen"),
  newIsoCountry("YU", "Yugoslavia"),
  newIsoCountry("ZM", "Zambia"),
  newIsoCountry("ZW", "Zimbabwe"),
];

/**
 * Ported from `IsoCountries.Find(string value)`. C# used
 * `StringComparison.InvariantCultureIgnoreCase` for both the 2-letter-code
 * and name comparisons -- plain `.toLowerCase()` comparison is the
 * practical TS equivalent here (this list is fixed, all-ASCII-Latin data).
 *
 * `value.Length == 3` matches on just the *first two* characters of the
 * 3-character input against `TwoLetterCode` (not `ThreeLetterCode` --
 * `IsoCountry` doesn't have one) -- preserved as-is, faithful to the C#
 * source even though it reads oddly (it's a quirk of the original, not
 * something to "fix" here).
 *
 * C#'s `SingleOrDefault` throws `InvalidOperationException` if more than
 * one match exists; `.find()` would silently return the first. This list
 * has no duplicate two-letter codes or names, so the distinction is not
 * observable in practice -- documented here rather than replicating the
 * throw-on-multiple-matches behavior with extra code for a case that can't
 * occur with this fixed dataset.
 */
export function findIsoCountry(value: string | null | undefined): IsoCountry | undefined {
  if (value === null || value === undefined || value.trim() === "") {
    return undefined;
  }

  if (value.length === 2) {
    return All.find((c) => c.twoLetterCode.toLowerCase() === value.toLowerCase());
  } else if (value.length === 3) {
    const prefix = value.substring(0, 2).toLowerCase();
    return All.find((c) => c.twoLetterCode.toLowerCase() === prefix);
  } else {
    return All.find((c) => c.name.toLowerCase() === value.toLowerCase());
  }
}

export const IsoCountries = {
  All,
  Find: findIsoCountry,
} as const;
